#!/bin/bash
# Regenerate src/apps_local/clippy/ClippyArt.h from assets_local/clippy/.
#
#   brew install librsvg          # rsvg-convert, the only external dependency
#   ./tools_local/clippy/gen_clippy_art.sh
#
# The output is committed, because regenerating needs librsvg and a checkout
# should build without it. Edit the SVG, run this, commit both.
#
# The SDK's own icon generator, pointed at our SVG instead of Lucide's, exactly
# the way tools_local/jaipur/gen_jaipur_art.sh does. Nothing here is new
# machinery; the only choice is the two cuts, and clippy_art.txt says why.
#
# THE FALLBACK. The header currently in the tree was NOT produced by this
# script: the machine it was written on has no rsvg-convert and no uv, so
# tools_local/clippy/rasterize_clippy.py drew it from the same SVG with the
# standard library alone. Its banner says so, so you can always tell which one
# you are looking at. This script is the canonical path -- run it as soon as
# librsvg is available and commit the result, which will differ in the low bits
# (real antialiasing, and none of the fallback's minimum-stroke hinting).
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/clippy/clippy_art.txt \
  --svgdir assets_local/clippy \
  --sizes 32,240 \
  --out src/apps_local/clippy/ClippyArt.h

# The generator hardcodes "from Lucide SVGs" in its banner, which is a lie in
# this file. Asserted rather than sed'd blind: if the SDK reworks its banner
# this stops the build instead of leaving the wrong provenance behind.
OUT=src/apps_local/clippy/ClippyArt.h
WRONG="// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit."
RIGHT="// Generated by tools_local/clippy/gen_clippy_art.sh from assets_local/clippy/*.svg. Do not edit."
grep -qF "$WRONG" "$OUT" || { echo "gen_icons.py banner changed; update gen_clippy_art.sh" >&2; exit 1; }
uv run --quiet python -c "
import sys
path, wrong, right = sys.argv[1:4]
text = open(path).read()
assert text.count(wrong) == 1
open(path, 'w').write(text.replace(wrong, right))
" "$OUT" "$WRONG" "$RIGHT"

./bin/clang-format-fix >/dev/null 2>&1 || clang-format -i "$OUT"
echo "wrote $OUT"
