#!/usr/bin/env python3
"""ClippyArt.h from a raster picture of Clippy instead of the SVG.

The SVG pipeline (gen_clippy_art.sh, rasterize_clippy.py) draws a paperclip
from shapes. This reads a painting of one -- the classic render, shaded and on
its yellow notepad -- and reduces it to the one bit the panel has.

Three steps, each of which is a choice about what survives:

  1. THE NOTEPAD GOES. It is the only thing in the picture that is yellow, so
     yellow (red and green both well above blue) is painted white before
     anything else is decided. Thresholded instead, the paper's shading would
     come out as a speckled slab behind the clip.

  2. TRANSPARENCY IS WHITE. The PNG has a clear background; every pixel is
     composited on white first, so the soft edge of the clip fades to paper
     rather than to black.

  3. INK IS ANYTHING DARKER THAN `--threshold`. The clip's tube is a mid
     purple with a light highlight down its length. gen_icons.py's 110 would
     keep only the shadowed side and lose the tube, so the default here is
     higher: the whole tube goes black and the highlight with it, which is what
     a flat 1-bit paperclip should look like. The eyes are white on the far side
     of the cut, the pupils and brows black on the near side.

Downscaling happens in greyscale BEFORE the threshold, so the antialiasing does
the shape work and the threshold decides once. Emits the same header, in the
same format, through rasterize_clippy.py's own pack() and wrapped(), so the two
generators cannot disagree about the byte order.

Usage:
    python3 tools_local/clippy/png_to_clippy_art.py \
        --png <clippy.png> --alias clippy --sizes 32,240 \
        --out src/apps_local/clippy/ClippyArt.h [--preview <dir>]
"""
import argparse
import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rasterize_clippy import pack, wrapped  # noqa: E402

# Yellow: red and green both this much above blue. The notepad's pixels sit
# around (238, 230, 146); the clip's purple around (165, 161, 193) has blue on
# top and never qualifies, and the greys of the eyes have no spread at all.
YELLOW_SPREAD = 40

# Luminance below this is ink. See step 3 above for why it is not 110.
DEFAULT_THRESHOLD = 200


def load_figure(path):
    """The picture on white, notepad removed, cropped to the figure, square."""
    image = Image.open(path).convert("RGBA")
    white = Image.new("RGBA", image.size, (255, 255, 255, 255))
    pixels = image.load()
    width, height = image.size
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            if r - b >= YELLOW_SPREAD and g - b >= YELLOW_SPREAD:
                pixels[x, y] = (255, 255, 255, 0)
    flat = Image.alpha_composite(white, image).convert("L")
    # Crop to what is drawn, then pad to a square around it so the cut is not
    # stretched: the icon is w == h by contract.
    inverted = Image.eval(flat, lambda v: 255 - v)
    box = inverted.getbbox()
    if box is None:
        sys.exit("png_to_clippy_art.py: the picture is blank once the notepad is removed")
    figure = flat.crop(box)
    side = max(figure.size)
    square = Image.new("L", (side, side), 255)
    square.paste(figure, ((side - figure.size[0]) // 2, (side - figure.size[1]) // 2))
    return square


def rows_at(square, px, threshold):
    """px-by-px rows of booleans, True where black."""
    scaled = square.resize((px, px), Image.LANCZOS)
    data = scaled.load()
    return [[data[x, y] < threshold for x in range(px)] for y in range(px)]


def preview(rows, px, path):
    image = Image.new("1", (px, px), 1)
    data = image.load()
    for y in range(px):
        for x in range(px):
            if rows[y][x]:
                data[x, y] = 0
    image.save(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png", required=True)
    ap.add_argument("--alias", required=True)
    ap.add_argument("--sizes", default="32,240")
    ap.add_argument("--threshold", type=int, default=DEFAULT_THRESHOLD)
    ap.add_argument("--out", required=True)
    ap.add_argument("--preview", help="directory to write a 1-bit PNG of each cut into")
    args = ap.parse_args()
    sizes = [int(s) for s in args.sizes.split(",")]
    square = load_figure(args.png)

    out = [
        "#pragma once",
        "",
        '#include "Icon.h"',
        "",
        "// Generated by tools_local/clippy/png_to_clippy_art.py from a raster picture of Clippy.",
        "// Do not edit. NOT the SVG pipeline: gen_clippy_art.sh and rasterize_clippy.py draw",
        "// assets_local/clippy/clippy.svg instead; this thresholds a painting. One or the other.",
        f"// Sizes: {', '.join(str(s) for s in sizes)}px. Icons: 1. Threshold: {args.threshold}.",
        "",
    ]
    for px in sizes:
        rows = rows_at(square, px, args.threshold)
        if args.preview:
            os.makedirs(args.preview, exist_ok=True)
            preview(rows, px, os.path.join(args.preview, f"{args.alias}_{px}.png"))
        data, center = pack(rows, px)
        arr = f"icon_{args.alias}_{px}_bits"
        out.append(wrapped(f"static const uint8_t {arr}[] = {{", [f"0x{b:02X}" for b in data], "};"))
        out.append(f"static const freeink::Icon icon_{args.alias}_{px} = {{{px}, {px}, {center}, {arr}}};")
    out.append("")
    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out))
    print(f"wrote {args.out}: 1 icon x {len(sizes)} sizes, threshold {args.threshold}")


if __name__ == "__main__":
    main()
